- name: Install gitea 
  hosts: "{{ target_hosts }}"
  roles: 
    - geerlingguy.gitlab
  vars: 
    gitlab_domain: "{{ wf_ec2_instance_facts.instances[0].public_dns_name }}"
    gitlab_external_url: "https://{{ gitlab_domain }}/"
    gitlab_git_data_dir: "/var/opt/gitlab/git-data"
    gitlab_backup_path: "/var/opt/gitlab/backups"
    gitlab_edition: "gitlab-ce"
