- name: Install gitea 
  hosts: "{{ target_hosts }}"
  roles: 
    - do1jlr.gitea
  vars: 
    gitea_fqdn: "{{ wf_ec2_instance_facts.instances[0].public_dns_name }}"
    gitea_root_url: "http://{{wf_ec2_instance_facts.instances[0].public_dns_name}}"
    gitea_protocol: http
    gitea_start_ssh: true

  pre_tasks: 
    - name: install necessary packages 
      yum:
        name:  
          - firewalld
          - httpd
        state: latest

    - name: start services
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - httpd
        - firewalld