- name: Install gitea 
  hosts: "{{ target_hosts }}"
  roles: 
    - do1jlr.gitea
  vars: 
    #gitea_fqdn: 'git.example.com'
    gitea_root_url: 'https://' + {{ ec2_instance_facts.instances[0].public_ip_address }}
    gitea_protocol: https
    gitea_start_ssh: true